---
- name: Install all rpms
  yum:
    name: "{{item}}"
    state: present
    disable_gpg_check: yes
  with_items:
    - "/opt/ancillary_local/OO416/en-US/RPMS/{{open_office_rpms}}"
  when: custom_repo
